### ISSUE TITLE
PS Module for BackupRestoreService from ServiceFabric team is in Preview

### ISSUE THREAD

**Issue by hrushib** [Sweiii/Service-Fabric-BackupRestoreService#1]
Hi @Sweiii,

Thanks for your efforts and support for making use of ServiceFabric easier. Please note that ServiceFabric team is in process of releasing PS Module containing support for all existing BackupRestoreService APIs - [
Microsoft.ServiceFabric.Powershell.Http Powershell Module](https://github.com/Microsoft/service-fabric-client-dotnet/blob/develop/docs/SFPowershellUsage.md). Please have a look at it to see if you can re-use.

Thanks,
Hrushikesh

**Comment by Sweiii** [comment]
Thanks for the info, i had missed that one. Will look at it when i get to work.
